### ISSUE TITLE
Unable to use function declared in a separate file

### ISSUE THREAD

**Issue by ghoullier** [WarpJS/beta#15]
## index.js
```js
import { defaultWarper as warper } from '@warpjs/warp';
import engine from '@warpjs/engine';

import { hello } from './api';

engine.init({ config: { logging: 'info' } });

engine.setErrorHandler((error) => {
  console.error('WarpJSError', error);
});

document.addEventListener('DOMContentLoaded', async () => {
  const message = await warper.call(hello);
  console.log(message);
});
```

## api.js
```js
export function hello() {
  'warp +server -client';

  return `hello from Node`;
}
```

## Error
```console
ERROR in ./src/api.js
Module build failed (from ./node_modules/@warpjs/webpack-plugin/lib/warpifyLoader):
TypeError: Cannot read property '0' of undefined
    at g (/Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:40556)
    at d.insertDeclarationsWrappers (/Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:37743)
    at Object.addHelperFunctions (/Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:40961)
    at /Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:44883
    at Set.forEach (<anonymous>)
    at m.instrumentAtEndOfPipe (/Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:44785)
    at instrumentSourceBasedOnTags (/Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:30242)
    at Object.e.exports (/Users/ghoullier/Dev/ghoullier/warp-experiments/node_modules/@warpjs/webpack-plugin/lib/warpifyLoader.js:1:77632)
 @ ./src/index.js 48:0-30 71:36-41 86:42-47
```

If  my `hello` function declared in the index file, there is no problem.

**Comment by jpl-scale** [comment]
Thanks for your report. There is an issue about the error reporting, and one in the doc.

**Comment by scajegou** [comment]
The problem comes from the export statement declaring a function. You can use this workaround:

``` javascript
function hello() {
  'warp +server -client';

  return `hello from Node`;
}
export { hello };
```

**Comment by ghoullier** [comment]
Thanks for your workaround 👍

**Comment by NicolasPennec** [comment]
The documentation has been updated: https://warpjs.dev/docs/api/requirements#ecmascript-support
