### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by Stef-SD** [WarpJS/beta#4]
I can't use the [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document) interface in my WarpJS warped function.

> var wordElement = document.createElement('ul'); // create single word element 

```
engine-prod.js:30 Uncaught (in promise) 
ReferenceError {stack: "ReferenceError: document is not defined↵    at fn …ndRejections (internal/process/next_tick.js:81:5)", message: "document is not defined"}
stack: "ReferenceError: document is not defined↵    at fn (eval at buildAndEvalEnvironment (/home/stef/dev/heart-of-words/.warp/server-emulation/node_modules/@warpjs/flow-server/flowServer.js:18:20209), <anonymous>:196:23)↵    at fn (eval at buildAndEvalEnvironment (/home/stef/dev/heart-of-words/.warp/server-emulation/node_modules/@warpjs/flow-server/flowServer.js:18:20209), <anonymous>:56:9)↵    at fn (eval at buildAndEvalEnvironment (/home/stef/dev/heart-of-words/.warp/server-emulation/node_modules/@warpjs/flow-server/flowServer.js:18:20209), <anonymous>:9:5)↵    at Flow.flowRun (/home/stef/dev/heart-of-words/.warp/server-emulation/node_modules/@warpjs/flow-server/flowServer.js:18:7073)↵    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
message: "document is not defined"
__proto__: Error
```

@warpjs/webpack-plugin: ^1.1.0-rc1
@warpjs/engine: ^1.1.0-rc1

**Comment by jpl-scale** [comment]
@scajegou could you please see how we can have a better stack trace here?

**Comment by jpl-scale** [comment]
We will add clarification in documentation. Thank you.

**Comment by scajegou** [comment]
The ugly stack trace display is because of an issue with the errors serialization / deserialization.
I'm looking into it
