### ISSUE TITLE
FetchError

### ISSUE THREAD

**Issue by cnabot-scale** [WarpJS/beta#5]
```
FetchError: invalid json response body at https://starbase.warpjs.com/signup/4gdwLB8actVUyPQKkynWHe/build/get-config reason: Unexpected token < in JSON at position 0
    at /home/obiwan/Documents/webpack-demos/demo01/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by jpl-scale** [comment]
This is due to a wrong setting of an internal option.
